spring:
  application:
    name: api-gateway


zuul:
  routes:
    order:
      path: /order/**
      url: http://localhost:8081
      stripPrefix: false
    warehouse:
      path: /warehouse/**
      url: http://localhost:8082
      stripPrefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true